type t =
  | @as("single") SINGLE
  | @as("words") WORDS
  | @as("double") DOUBLE
  | @as("thick") THICK
  | @as("dotted") DOTTED
  | @as("dottedHeavy") DOTTEDHEAVY
  | @as("dash") DASH
  | @as("dashedHeavy") DASHEDHEAVY
  | @as("dashLong") DASHLONG
  | @as("dashLongHeavy") DASHLONGHEAVY
  | @as("dotDash") DOTDASH
  | @as("dashDotHeavy") DASHDOTHEAVY
  | @as("dotDotDash") DOTDOTDASH
  | @as("dashDotDotHeavy") DASHDOTDOTHEAVY
  | @as("wave") WAVE
  | @as("wavyHeavy") WAVYHEAVY
  | @as("wavyDouble") WAVYDOUBLE
  | @as("none") NONE
